@baseAddress = https://localhost:7206

GET {{baseAddress}}/products
Accept: application/json

###
POST {{baseAddress}}/products
Content-Type: application/json

{
  "name": "novissimo",
  "category": "plus",
  "unitCost": 56.23
}

###
GET {{baseAddress}}/products/1
Accept: application/json

### 
PUT {{baseAddress}}/products/2
Content-Type: application/json

{
  "name": "novissimo-updated",
  "category": "premium",
  "unitCost": 99.99
}

###
DELETE {{baseAddress}}/products/2
